#file: noinspection KubernetesUnknownValues
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: admin-server
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ "/bin/sh", "-c","until nc config-server 8888 -w1 ; do sleep 2; done" ]
      containers:
      - image: neiltingley/spring-petclinic-admin-server:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
          - name: CONFIG_SERVER_URL
            value: http://config-server:8888
          - name: NODE_NAME
            value: admin-server
        name: admin-server
        ports:
          - containerPort: 9090
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}
