apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: discovery-server
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ["/bin/sh", "-c","until nc config-server 8888 -w1 ; do sleep 2; done" ]
      containers:
        - image: neiltingley/spring-petclinic-discovery-server:latest
          name: discovery-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always

