{{ if .Values.prometheus }}

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: prometheus-server
    spec:
      containers:
        - image: prometheus-server
          name: prometheus-server
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: 500Mi
      restartPolicy: Always
  {{- end }}
