apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: tracing-server
  name: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tracing-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: tracing-server
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: [ "/bin/sh", "-c","until nc config-server 8888 -w1 ; do sleep 2; done" ]
      containers:
        - env:
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: NODE_NAME
              value: customers-service
          image: openzipkin/zipkin
          name: tracing-server
          ports:
            - containerPort: 9411
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always
status: {}
