apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-admin-server
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: admin-server
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-api-gateway
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-config-server
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-customers-service
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-discovery-server
        ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-vets-service
        ports:
          - containerPort: 8080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:

      containers:
      - name: visits-service
        imagePullPolicy: IfNotPresent
        image: neiltingley/spring-petclinic-visits-service
        ports:
          - containerPort: 8080
