{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "spring-petclinic.serviceLabels" (dict "root" $ "name" $serviceName) | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $service.service.type }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "spring-petclinic.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}
