pipeline:
  identifier: Build_neiltingley_spring_petclinic_microservices_1755532919492
  name: Build spring-petclinic-microservices
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1755532883985
        repoName: neiltingley/spring-petclinic-microservices
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
